// Copyright (c) Márk Csörgő and Martin Bartos
// Licensed under the MIT License. See LICENSE file for details.

using System;
using avallama.Services;
using CommunityToolkit.Mvvm.ComponentModel;

namespace avallama.Models;

#region Message

/// <summary>
/// Represents a message within a conversation.
/// </summary>
public class Message : ObservableObject
{
    /// <summary>
    /// Gets or sets the unique identifier of the message.
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the textual content of the message.
    /// </summary>
    public string Content
    {
        get;
        set => SetProperty(ref field, value);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Message"/> class.
    /// </summary>
    /// <param name="content">The content of the message.</param>
    public Message(string content)
    {
        Content = content;
    }
}

#endregion

#region GeneratedMessage

/// <summary>
/// Represents a message generated by a language model.
/// </summary>
public class GeneratedMessage : Message
{
    /// <summary>
    /// Gets or sets the generation speed in tokens per second.
    /// </summary>
    public double GenerationSpeed
    {
        get;
        set => SetProperty(ref field, Math.Round(value, 2));
    }

    /// <summary>
    /// Initializes a new empty instance of the <see cref="GeneratedMessage"/> class.
    /// </summary>
    public GeneratedMessage() : base(string.Empty)
    {
        GenerationSpeed = 0.0;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GeneratedMessage"/> class with content and speed.
    /// </summary>
    /// <param name="content">The generated text content.</param>
    /// <param name="generationSpeed">The speed of generation in tokens per second.</param>
    public GeneratedMessage(string content, double generationSpeed) : base(content)
    {
        GenerationSpeed = generationSpeed;
    }
}

#endregion

#region UI specific messages

// these message types are inevitable as ui needs to know what message to render and how
// must be excluded from saving into db or sending as context to ollama

/// <summary>
/// Represents a message indicating a failed generation or connection error.
/// </summary>
public class FailedMessage : Message
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FailedMessage"/> class.
    /// </summary>
    /// <param name="content">The error content.</param>
    public FailedMessage(string content = "") : base(content)
    {
        Id = -1;
    }
}

/// <summary>
/// Represents a visual indicator showing that the message is being processed.
/// </summary>
public class TypingIndicatorMessage : Message
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TypingIndicatorMessage"/> class.
    /// </summary>
    public TypingIndicatorMessage() : base(string.Empty)
    {
        Id = -1;
    }
}

#endregion


